server:
  port: 8082
# The values given here are actually the default values. But they are explicitly
# set here as an example of setting the Kafka properties.
spring:
  kafka:
    bootstrap-servers:
    - localhost:9092
    template:
      default-topic: deepatopic2
    producer:
      keySerializer: org.springframework.kafka.support.serializer.JsonSerializer
      valueSerializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      properties:
        metadata.max.age.ms: 0
        max.poll.interval.ms: 1
      keyDeserializer: org.apache.kafka.common.serialization.StringDeserializer
      valueDeserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false
      auto-commit-interval: 1000
      auto-offset-reset: earliest
      
    listener:
      ack-mode: manual
    
        
        
      
      
        